language: node_js
node_js:
    - node
    - '7'
    - '6'
sudo: false
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install
    - npm install -g mocha
script:
    - mocha test/js --recursive
notifications:
    email: false
